# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'firebaseExmpl' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]
  
  # Pods for firebaseExmpl
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  # pod 'Firebase/Crash'
  pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  # pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  
  pod 'react-native-fbsdk', :subspecs => [
    'Core',
    'Login',
    'Share',
  ], :path => '../node_modules/react-native-fbsdk/iOS'

  target 'firebaseExmplTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firebaseExmpl-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseExmpl-tvOS

  target 'firebaseExmpl-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    
    if target.name == "React"
      target.remove_from_project
    end
  end
end
